name: Pull Request Preview

on: [pull_request]

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies for Next.js Build
        run: npm ci

      - name: Run Next.js build to generate the static files
        run: npm run build

        # Runs the deploy command
        # Parses the output, and 
        # retrieves the build log url & the deployed url,
        # finally stores them into variables: NETLIFY_LOGS_URL & NETLIFY_LIVE_URL
      - name: üöÄ Deploy
        id: deploy-netlify
        run: |
          COMMAND="netlify deploy \
          --build -m ${{ github.head_ref }} \
          --alias ${{ github.head_ref }}"
          OUTPUT=$(sh -c "$COMMAND")

          NETLIFY_URL=$(echo "$OUTPUT" \
          | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*')
          # Unique key: --
          
          NETLIFY_LOGS_URL=$(echo "$OUTPUT" \
          | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')
          # Unique key: app.netlify.com

          echo "::set-output name=netlify_preview_url::$NETLIFY_URL"
          echo "::set-output name=netlify_logs_url::$NETLIFY_LOGS_URL"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # Publish the inspect and preview link to the PR
      - name: üëì Netlify Preview URL
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: |
            This pull request is being automatically deployed to Netlify
            üîç Inspect: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}
            ‚úÖ Preview: ${{ steps.deploy-netlify.outputs.NETLIFY_PREVIEW_URL }}

        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: true
